dataset: 'scannet'
meshing:
  eval_rec: True
  resolution: 0.02
tracking:
  vis_freq: 4000000
  vis_inside_freq: 25
  ignore_edge_W: 75
  ignore_edge_H: 75
  seperate_LR: True
  const_speed_assumption: True
  lr: 0.0005
#  lr: 0.002
  pixels: 2000
  iters: 30
mapping:
  every_frame: 4
  vis_freq: 4000000
  vis_inside_freq: 30
  mesh_freq: 4000000
  ckpt_freq: 500
  keyframe_every: 4
  mapping_window_size: 20
  pixels: 4000
  iters_first: 1000
  iters: 30
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 10
rendering:
  N_samples: 32
  N_surface: 8
  N_importance: 8
  lindisp: False
  perturb: 1.0