dataset: 'scannet'
tracking:
  vis_freq: 4000000
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.0005
  pixels: 1000
  iters: 50
mapping:
  every_frame: 4
  vis_freq: 40
  vis_inside_freq: 30
  mesh_freq: 4000000
  ckpt_freq: 500
  keyframe_every: 40
  mapping_window_size: 10
  pixels: 20000
  iters_first: 1500
  iters: 60
cam: 
  H: 480 
  W: 640
  fx: 577.590698
  fy: 578.729797
  cx: 318.905426
  cy: 242.683609
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 10