inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
  marching_cubes_bound: [[-0.2,9.8],[-1.0,8.5],[-1.0,3.4]]
data:
  input_folder: /idiap/temp/mjohari/Datasets/scannet/scans/scene0169_00
#  output: /idiap/temp/mjohari/outputs/slam/scannet/s169_imp_w20_cl2_glob_sep5_imp_cl5_nru_tail50_dl110_nmsk
  output: /idiap/temp/mjohari/outputs/slam/CVPR_4/ScanNet/scene0169/ours_0