inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
  marching_cubes_bound: [[0.3,9.9],[-1.0,8.0],[-1.0,3.8]]
data:
  input_folder: /idiap/temp/mjohari/Datasets/scannet/scans/scene0207_00
#  output: /idiap/temp/mjohari/outputs/slam/scannet/s207_imp_w20_cl6_glob_sep5_imp_cl5_nru_tail50_dl15_nmsk_w10_last2
  output: /idiap/temp/mjohari/outputs/slam/CVPR_4/ScanNet/scene0207/ours_0