inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-0.9,7.3],[-1.0,9.6],[-1.0,3.7]]
  marching_cubes_bound: [[-0.9,7.3],[-1.0,9.6],[-1.0,3.7]]
data:
  input_folder: /idiap/temp/mjohari/Datasets/scannet/scans/scene0059_00
  output: /idiap/temp/mjohari/outputs/slam/scannet/s59_imp_w20_cl6_glob_sep5_imp_cl5_nru_tail50_dl110_nmsk