inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-1.0,8.9],[-0.9,8.0],[-1.0,3.6]]
  marching_cubes_bound: [[-1.0,8.9],[-0.9,8.0],[-1.0,3.6]]
data:
  input_folder: /idiap/temp/mjohari/Datasets/scannet/scans/scene0181_00
  output: /idiap/temp/mjohari/outputs/slam/scannet/s181_over20_ign75
#  output: /idiap/temp/mjohari/outputs/slam/scannet/s181_temp2