inherit_from: configs/ScanNet/scannet.yaml
mapping:
  bound: [[-1.0,8.9],[-0.9,8.0],[-1.0,3.6]]
  marching_cubes_bound: [[-1.0,8.9],[-0.9,8.0],[-1.0,3.6]]
data:
  input_folder: /idiap/temp/mjohari/Datasets/scannet/scans/scene0181_00
  output: /idiap/temp/mjohari/outputs/slam/scannet/s181_imp_w20_cl2_glob_sep5_imp_cl5_nru_tail50_dl110_nmsk
#  output: /idiap/temp/mjohari/outputs/slam/scannet/s181_temp