inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-5.3,6.5],[-5.1,6.0],[-4.5,5.2]]
  marching_cubes_bound: [[-5.3,6.5],[-5.1,6.0],[-4.5,5.2]]
data:
  input_folder: /idiap/resource/database/ETHZ-Replica/office1
  output: /idiap/temp/mjohari/outputs/slam/Replica/o1_temp
