dataset: 'replica'
meshing:
  eval_rec: True
tracking:
  vis_freq: 5000
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.001
  pixels: 200
  iters: 20
mapping:
  every_frame: 1
  vis_freq: 5000
  vis_inside_freq: 50
  mesh_freq: 20000
  ckpt_freq: 5000
  keyframe_every: 10
  mapping_window_size: 10
  pixels: 1500
  iters_first: 1500
  iters: 15
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0