dataset: 'replica'
meshing:
  resolution: 0.01
tracking:
  seperate_LR: False
  lr: 0.001
  pixels: 2000
  iters: 8
mapping:
  pixels: 4000
  iters: 15
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
rendering:
  N_samples: 32
  N_surface: 8