dataset: 'replica'
meshing:
  eval_rec: True
  resolution: 0.01
tracking:
  vis_freq: 40000000000
  vis_inside_freq: 25
  ignore_edge_W: 100
  ignore_edge_H: 100
  seperate_LR: False
  const_speed_assumption: True
  lr: 0.001
  pixels: 2000
  iters: 8
mapping:
  every_frame: 4
  vis_freq: 4000000000
  vis_inside_freq: 12
  mesh_freq: 4000000000
  ckpt_freq: 5000
  keyframe_every: 4
  mapping_window_size: 20
  pixels: 4000
  iters_first: 1000
  iters: 15
cam:
  H: 680
  W: 1200
  fx: 600.0
  fy: 600.0
  cx: 599.5
  cy: 339.5
  png_depth_scale: 6553.5 #for depth image in png format
  crop_edge: 0
rendering:
  N_samples: 32
  N_surface: 8
  N_importance: 0
  lindisp: False
  perturb: 1.0