inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-6.0,1.8],[-3.6,3.3],[-2.0,1.9]]
#  bound: [[-5.5,1.3],[-3.1,2.8],[-1.5,1.4]]
  marching_cubes_bound: [[-6.0,1.8],[-3.6,3.3],[-2.0,1.9]]
data:
  input_folder: /idiap/resource/database/ETHZ-Replica/room1
  output: /idiap/temp/mjohari/outputs/slam/Replica/r1_sanity_dl01_t06_bound_hr
#  output: /idiap/temp/mjohari/outputs/slam/Replica/r1_nice