inherit_from: configs/Replica/replica.yaml
mapping:
  bound: [[-4.3,9.5],[-6.7,5.2],[-6.4,4.2]]
  marching_cubes_bound: [[-4.3,9.5],[-6.7,5.2],[-6.4,4.2]]
data:
  input_folder: /idiap/resource/database/ETHZ-Replica/room0
  output: output/Replica/room2